### PR TITLE
Initial file structure + password generator module

### PR DESCRIPTION
**Pull request by Ernest1338**
New file structure:
```
|PixelToolkit
|- modules
|-- lib
|--- lib_gui.py
|--- lib_tui.py
|--- lib_pass_gen.py
|-- pass_gen.py
|- README.md
|...
```

### CODE REVIEW

**Comment by Ernest1338** [comment]
For now I choose to put the lib directory inside of the modules directory as this makes it easier to import lib files from the module files. This might not be the final solution.

**Comment by Ernest1338** [comment]
As the CLI part of the toolkit I choose to use Python's Argparse library. It should be preinstalled on every python install. (At least I have it already and don't remember installing it :sweat_smile:)

**Comment by Ernest1338** [comment]
Also I don't think it makes sense to make a separate lib_cli.py file as it would be a straight re-export of argparse functions. They are simple enough by default

**Review by GrzegorzSzczepanek — APPROVED** [review]
lgtm

**Pull request merged**
